"""PyInstaller recipe for the Windows one-file companion executable.

The recipe resolves its source tree from the spec location, so it remains valid
when the companion is exported from the private ```` subtree to a public
repository root.

Build through ``python build.py`` rather than invoking this spec directly.
The script derives the Windows file metadata from ``overanalyzer_agent.__version__``
and then supplies the generated resource file here.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path


AGENT_DIR = Path(SPECPATH).resolve()
sys.path.insert(0, str(AGENT_DIR))

from overanalyzer_agent import __version__  # noqa: E402


if os.environ.get("OA_AGENT_BUILD_VERSION") != __version__:
    raise SystemExit(
        "Build through python build.py so the executable metadata uses "
        "overanalyzer_agent.__version__."
    )

VERSION_INFO = os.environ.get("OA_AGENT_VERSION_INFO")
if not VERSION_INFO or not Path(VERSION_INFO).is_file():
    raise SystemExit("build.py did not provide the generated Windows version resource.")

# The taskbar/Explorer icon. Generated by build.py from ui.brand, so the icon on
# a downloaded EXE is the same mark the running app draws. Without it Windows
# shows PyInstaller's default, which is the first thing a stranger sees.
ICON = os.environ.get("OA_AGENT_ICON")
if not ICON or not Path(ICON).is_file():
    raise SystemExit("build.py did not provide the generated application icon.")

# Several modules are imported only after a user chooses a tray, panel, or
# capture path. Keep them explicit so a frozen build has the same runtime
# surface as source, even though the entry point imports them lazily.
HIDDEN_IMPORTS = [
    "keyboard",
    "mss",
    "pystray",
    "pystray._win32",
    "tomli_w",
    "PIL.ImageTk",
    "overanalyzer_agent.capture",
    "overanalyzer_agent.hotkeys",
    "overanalyzer_agent.matchinfo",
    "overanalyzer_agent.session",
    "overanalyzer_agent.tray",
    "overanalyzer_agent.window",
    "overanalyzer_agent.ui.assets",
    "overanalyzer_agent.ui.brand",
    "overanalyzer_agent.ui.fonts",
    "overanalyzer_agent.ui.icons",
    "overanalyzer_agent.ui.layout",
    "overanalyzer_agent.ui.sound",
    "overanalyzer_agent.ui.surface",
    "overanalyzer_agent.ui.toast",
    "overanalyzer_agent.ui.topography",
]

a = Analysis(
    [str(AGENT_DIR / "overanalyzer_agent" / "__main__.py")],
    pathex=[str(AGENT_DIR)],
    binaries=[],
    # The source resolves fonts and role art from <bundle>/assets.  A one-file
    # executable extracts this explicit tree to that same location at startup.
    datas=[(str(AGENT_DIR / "assets"), "assets")],
    hiddenimports=HIDDEN_IMPORTS,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="OverAnalyzer",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    version=VERSION_INFO,
    icon=ICON,
)
